config/routes.rb
ScoringSystemLogic::Application.routes.draw do
  devise_for :users

  get "member/index"

  resources :predictions, :only => [:index, :new, :create]
  resources :fixtures, :only => [:index, :new, :create]

  post "predictions/create"

   root :to => 'member#index'

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  attr_accessible :away_team, :fixture_date, :home_team, :kickoff_time, :prediction_id


end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  attr_accessible :away_score, :away_team, :fixture_id, :home_score, :home_team, :score, :fixture_date, :user_id

  has_one :fixture
  has_one :result
 
end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :away_score, :away_team, :fixture_date, :home_score, :home_team, :prediction_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :predictions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController

def index
    @fixtures = Fixture.all
  end

  def new
    @fixture = Fixture.new
  end

  def create 
    @fixture = Fixture.new(params[:fixture])
    if @fixture.save
      redirect_to root_path
    else
      render :new
    end
  end
  
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
	before_filter :authenticate_user!
  def index
  	three_days_from_today = Date.today - 3
    @fixtures = Fixture.where("fixture_date <= ?", three_days_from_today)
    @fixture_date = @fixtures.group_by {|fd| fd.fixture_date}

    previous_three_days = Date.today - 3
    @results = Result.where("fixture_date <= ?", previous_three_days).group("home_team, away_team, fixture_date")
    @result_date = @results.group_by {|r| r.fixture_date}

    @predictions = current_user.predictions.where("fixture_date <= ?", previous_three_days)
    @user_predictions = @predictions.group_by {|p| p.fixture_date}

    @weekly_points = current_user.predictions.where("fixture_date <= ?", previous_three_days).sum(:score)
  end
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
 

  def index
  	 previous_three_days = Date.today - 3
    @predictions = current_user.predictions.where("fixture_date >= ?", previous_three_days)
    @user_predictions = @predictions.group_by {|p| p.fixture_date}

  	

  end

	def new
     @prediction = Prediction.new
     three_days_from_today = Date.today - 3
     @fixtures = Fixture.where("fixture_date >= ?", three_days_from_today)
    @fixture_date = @fixtures.group_by {|fd| fd.fixture_date}
	end

	def create
    begin
      params[:predictions].each do |prediction|
        Prediction.new(prediction).save!
      end
      redirect_to root_path, :notice => 'Predictions Submitted Successfully'
    
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def login_status
    if user_signed_in?
      link_to("Logout", destroy_user_session_path, :confirm => "Are you sure you want to logout", :method => :delete)
    else
      link_to("Login", new_user_session_path)
    end
  end

  #Use Devise on any page
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/fixtures/index.html.erb
<h1>Fixtures#index</h1>
<p>Find me in app/views/fixtures/index.html.erb</p>

app/views/fixtures/new.html.erb
<h1>Fixtures#new</h1>
<p>Find me in app/views/fixtures/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScoringSystemLogic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
   <%= render 'shared/usernavbar' %>
   <% else %>
   <%= render 'shared/navbar' %>
  <% end %>
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/member/index.html.erb
    <div class="container">
      <div class="row">
        <div class="span4">
         <div class="well">
          <h2 class="muted">Make Predictions</h2>
           <%= form_tag controller: 'predictions', action: 'create', method: 'post' do %>
          
           <% @fixture_date.sort.each do |date, fixture| %>
           <ul class="fixture-dates">
           <li><h5><%= date %></h5></li>
           </ul>

           <ul class="fixtures">
           <% fixture.each do |fixture|%>
    
           <li>
            <span class="home-team"><%= fixture.home_team %></span> 
            <span class="score">
            <%= text_field_tag "predictions[][home_score]" %> 
            <%= text_field_tag "predictions[][away_score]" %>
            </span>
            <span class="away-team"><%= fixture.away_team %></span> 
          
           </li>
           <%= hidden_field_tag "predictions[][home_team]", fixture.home_team %>
           <%= hidden_field_tag "predictions[][away_team]", fixture.away_team %>

           <%= hidden_field_tag "predictions[][fixture_date]", fixture.fixture_date %>
           <%= hidden_field_tag "predictions[][fixture_id]", fixture.id %>
           <%= hidden_field_tag "predictions[][user_id]", current_user.id %>
          
         
           <% end %>
           </ul>
          <% end %>
          <%= submit_tag "Submit predictions", :class => "btn btn-success btn-large" %>
          <% end %>
        </div>
       </div>


    <div class="span4">
     <div class="well">
      <h2 class="muted">Previous Results</h2>

       <% @result_date.sort.each do |date, results| %>
       <ul class="fixture-dates">
        <li><h5><%= date %></h5></li>
       </ul>

         <ul class="fixtures">
         <% results.each do |result| %>
         <li>
          <span class="home-team"><%= result.home_team %></span>
          <span class="score">
            <%= result.home_score %> -
            <%= result.away_score %>
          </span>
          <span class="away-team"><%= result.away_team %></span>
        </li>
         <% end %>
         </ul>
        <% end %>
      
    </div>
    </div>

    <div class="span4">
    <div class="well">
    <h2 class="muted">Points Earned</h2>
         <% @user_predictions.sort.each do |date, prediction| %>
         <ul class="fixture-dates">
           <li><h5><%= date %></h5></li>
          </ul>
          
          <ul class="fixtures">
          <% prediction.each do |prediction| %>
          <li>
            <span class="home-team"><%= prediction.home_team %></span>
            <span class="score">
            <%= prediction.home_score %> -
            <%=  prediction.away_score %>
           </span>
            <span class="away-team"><%= prediction.away_team %></span>
            <span class="away-team"><%= prediction.score %></span>
          </li>

         <% end %>
          </ul>
         <% end %>
         <div class="span4">

          total points
          <%= @weekly_points %>
         </div>
    </div>
    </div>


   </div>
  </div>

app/views/predictions/index.html.erb
<div class="container">
  <div class="row">
    <div class="span4 offset1">
      <div class="well">
        <h2 class="muted">Current Predicitons</h2>
         <% @user_predictions.sort.each do |date, prediction| %>
         <ul class="fixture-dates">
           <li><h5><%= date %></h5></li>
          </ul>
          
          <ul class="fixtures">
          <% prediction.each do |prediction| %>
          <li>
            <span class="home-team"><%= prediction.home_team %></span>
            <span class="score">
            <%= prediction.home_score %> -
            <%=  prediction.away_score %>
           </span>
            <span class="away-team"><%= prediction.away_team %></span>
          </li>
         <% end %>
          </ul>
         <% end %>
      </div>
    </div>

    <div class="span4 offset1">
      <div class="well">
        <h2 class="muted">Previous Results</h2>

      </div>

    </div>

  </div>
<div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="../">Premier Predictions</a>
       <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav pull-right">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
       </div>
     </div>
   </div>
 </div>

app/views/shared/_usernavbar.html.erb
<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="../">Premier Predictions</a>
       <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav pull-right">
          <li><%= link_to "#{current_user.name}", edit_user_registration_path %></li>
          <li><%= link_to "My Predicitons", predictions_path %></li>
          <li><%= login_status %></li>  
       </div>
     </div>
   </div>
 </div>